In [1]:
import os
import json
import pandas as pd
import mysql.connector as db

In [2]:
#aggregated_insurance

path1 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/aggregated/insurance/country/india/state/"
aggre_insur_list = os.listdir(path1)

columns1={"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[], "Insurance_amount":[]}

for state in aggre_insur_list:
    cur_state = path1+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            A=json.load(data)
            #print(A)
            for i in A["data"] ["transactionData"]: #print this to get the field that to be sliced
                name = i["name"]
                #print(brand)
                count = i["paymentInstruments"][0]["count"]
                #print(count)
                amount = i["paymentInstruments"][0]["amount"]
                #print(amount)
                columns1["Insurance_type"].append(name)
                columns1["Insurance_count"].append(count)
                columns1["Insurance_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))
aggre_insurance = pd.DataFrame(columns1)

aggre_insurance["States"] = aggre_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar") # replace the value in dataframe as needed
aggre_insurance["States"] = aggre_insurance["States"].str.replace("-"," ") 
aggre_insurance["States"] = aggre_insurance["States"].str.title() #change all the states as Title
aggre_insurance['States'] = aggre_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#aggre_insurance

In [ ]:
#aggregated_transaction

path2 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/aggregated/transaction/country/india/state/"
aggre_trans_list = os.listdir(path2)

columns2={"States":[], "Years":[], "Quarter":[], "Trasaction_type":[], "Transaction_count":[], "Transaction_amount":[]}

for state in aggre_trans_list:
    cur_state = path2+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            B=json.load(data)
            for i in B["data"] ["transactionData"]: #print this to get the field that to be sliced
                name = i["name"]
                #print(name)
                count = i["paymentInstruments"][0]["count"]
                #print(count)
                amount = i["paymentInstruments"][0]["amount"]
                #print(amount)
                columns2["Trasaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["States"].append(state)
                columns2["Years"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

aggre_transaction = pd.DataFrame(columns2)


aggre_transaction["States"] = aggre_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_transaction["States"] = aggre_transaction["States"].str.replace("-"," ")
aggre_transaction["States"] = aggre_transaction["States"].str.title()
aggre_transaction['States'] = aggre_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#aggre_transaction

In [ ]:
#aggregated_user

path3 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/aggregated/user/country/india/state/"
aggre_user_list = os.listdir(path3)

columns3={"States":[], "Years":[], "Quarter":[], "Brands":[], "Transaction_count":[], "Percentage":[]}

for state in aggre_user_list:
    cur_state = path3+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            C=json.load(data)
            
            try:
                for i in C["data"] ["usersByDevice"]: #print this to get the field that to be sliced
                    brand = i["brand"]
                    #print(brand)
                    count = i["count"]
                    #print(count)
                    percentage = i["percentage"]
                    #print(percentage)
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))
            except:
                pass
aggre_user = pd.DataFrame(columns3)


aggre_user["States"] = aggre_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["States"] = aggre_user["States"].str.replace("-"," ")
aggre_user["States"] = aggre_user["States"].str.title()
aggre_user['States'] = aggre_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#aggre_user

In [4]:
#map_insurance

path4 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/map/insurance/hover/country/india/state/"
map_insur_list = os.listdir(path4)

columns4={"States":[], "Years":[], "Quarter":[], "District":[], "Transaction_count":[], "Transaction_amount":[]}

for state in map_insur_list:
    cur_state = path4+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            D=json.load(data)
            #print(D)
            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                #print(brand)
                count = i["metric"][0]["count"]
                #print(count)
                amount = i["metric"][0]["amount"]
                #print(amount)
                columns4["District"].append(name)
                columns4["Transaction_count"].append(count)
                columns4["Transaction_amount"].append(amount)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))

map_insurance = pd.DataFrame(columns4)

map_insurance["States"] = map_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["States"] = map_insurance["States"].str.replace("-"," ")
map_insurance["States"] = map_insurance["States"].str.title()
map_insurance['States'] = map_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#map_insurance

In [ ]:
#D["data"]["hoverDataList"][0]

In [ ]:
#map_transaction

path5 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/map/transaction/hover/country/india/state/"
map_trans_list = os.listdir(path5)

columns5={"States":[], "Years":[], "Quarter":[], "District":[], "Transaction_count":[], "Transaction_amount":[]}

for state in map_trans_list:
    cur_state = path5+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            E=json.load(data)
            #print(E)

            for i in E["data"] ["hoverDataList"]: #print this to get the field that to be sliced ------ D["data"] ["hoverDataList"][0]; print(D["data"] ["hoverDataList"][0]["metric"][0]["count"])
                name = i["name"]
                #print(brand)
                count = i["metric"][0]["count"]
                #print(count)
                amount = i["metric"][0]["amount"]
                #print(amount)
                columns5["District"].append(name)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

map_transaction = pd.DataFrame(columns5)

map_transaction["States"] = map_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_transaction["States"] = map_transaction["States"].str.replace("-"," ")
map_transaction["States"] = map_transaction["States"].str.title()
map_transaction['States'] = map_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#map_transaction

In [ ]:
#print(D["data"] ["hoverDataList"][0]["name"])

In [ ]:
#print(D["data"] ["hoverDataList"][0]["metric"][0]["count"])

In [ ]:
#map_user

path6 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path6)

columns6={"States":[], "Years":[], "Quarter":[], "District":[], "Registered_Users":[], "App_Opens":[]}

for state in map_user_list:
    cur_state = path6+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            F=json.load(data)
            #print(F)
            for i in F["data"]["hoverData"].items():
                district = i[0]
                #print(district)
                registeredUsers = i[1]["registeredUsers"]
                #print(registeredUsers)
                appOpens = i[1]["appOpens"]
                #print(amount)
                columns6["District"].append(district)
                columns6["Registered_Users"].append(registeredUsers)
                columns6["App_Opens"].append(appOpens)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))
map_user = pd.DataFrame(columns6)

map_user["States"] = map_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar") # replace the value in dataframe as needed
map_user["States"] = map_user["States"].str.replace("-"," ") 
map_user["States"] = map_user["States"].str.title() #change all the states as Title
map_user['States'] = map_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")
#map_user

In [ ]:
#for i in E["data"]["hoverData"].items():
    #print(i[0])
    #print(i[1]["registeredUsers"])
    #print(i[1]["appOpens"])

In [ ]:
#top_insurance
path7 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/top/insurance/country/india/state/"
top_insur_list = os.listdir(path7)

columns7 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_state = path7+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            G=json.load(data)
            #print(G)
            for i in G["data"]["pincodes"]:
                entityname = i["entityName"]
                #print(entityname)
                count = i["metric"]["count"]
                #print(count)
                amount = i["metric"]["amount"]
                #print(amount)
                columns7["Pincodes"].append(entityname)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))
top_insurance = pd.DataFrame(columns7)

top_insurance["States"] = top_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar") # replace the value in dataframe as needed
top_insurance["States"] = top_insurance["States"].str.replace("-"," ") 
top_insurance["States"] = top_insurance["States"].str.title() #change all the states as Title
top_insurance['States'] = top_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")
#top_insurance

In [ ]:
#top_transaction
path8 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/top/transaction/country/india/state/"
top_trans_list = os.listdir(path8)

columns8 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_trans_list:
    cur_state = path8+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            H=json.load(data)
            #print(H)

            for i in H["data"]["pincodes"]:
                entityname = i["entityName"]
                #print(entityname)
                count = i["metric"]["count"]
                #print(count)
                amount = i["metric"]["amount"]
                #print(amount)
                columns8["Pincodes"].append(entityname)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))
top_transaction = pd.DataFrame(columns8)

top_transaction["States"] = top_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar") # replace the value in dataframe as needed
top_transaction["States"] = top_transaction["States"].str.replace("-"," ") 
top_transaction["States"] = top_transaction["States"].str.title() #change all the states as Title
top_transaction['States'] = top_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")
#top_transaction

In [ ]:
#top_user
path9 = "D:/Gova/Data Science Course/Projects/2.Phonepe_Pulse_Data_Visualization/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path9)

columns9 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Registered_Users":[]}

for state in top_user_list:
    cur_state = path9+state+"/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year=cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file, "r")

            I=json.load(data)
            #print(H)
            for i in I["data"]["pincodes"]:
                entityname = i["name"]
                #print(entityname)
                registeredusers = i["registeredUsers"]
                #print(registeredUsers)
                columns9["Pincodes"].append(entityname)
                columns9["Registered_Users"].append(registeredusers)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))
top_user = pd.DataFrame(columns9)

top_user["States"] = top_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar") # replace the value in dataframe as needed
top_user["States"] = top_user["States"].str.replace("-"," ") 
top_user["States"] = top_user["States"].str.title() #change all the states as Title
top_user['States'] = top_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")
#top_user

In [12]:
#MySQL Connection
mydb = db.connect(
    host="localhost",
    port="3306",
    user="root",
    password="GovaMoni@Kanali26",
    database="phonepe_project")
mycursor = mydb.cursor()

#Table Creation
#Aggregated_Insurance_table

create_query_1 = '''CREATE TABLE IF NOT EXISTS aggregated_insurance(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    Insurance_type varchar(255),
                                                                    Insurance_count bigint,
                                                                    Insurance_amount bigint)'''
mycursor.execute(create_query_1)
mydb.commit()

insert_query_1 = '''INSERT INTO aggregated_insurance(States, Years, Quarter, Insurance_type, Insurance_count,
                                                    Insurance_amount)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = aggre_insurance.values.tolist()
mycursor.executemany(insert_query_1, data)
mydb.commit()

In [ ]:
#aggre_insurance.values.tolist()
#aggre_insurance.columns

In [15]:
#Aggregated_Transaction_table

create_query_2 = '''CREATE TABLE IF NOT EXISTS aggregated_transaction(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    Trasaction_type varchar(255),
                                                                    Transaction_count bigint,
                                                                    Transaction_amount bigint)'''
mycursor.execute(create_query_2)
mydb.commit()

insert_query_2 = '''INSERT INTO aggregated_transaction(States, Years, Quarter, Trasaction_type, Transaction_count,
                                                    Transaction_amount)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = aggre_transaction.values.tolist()
mycursor.executemany(insert_query_2, data)
mydb.commit()

In [ ]:
#aggre_transaction.columns #to check the columns

In [21]:
#Aggregated_User_table

create_query_3 = '''CREATE TABLE IF NOT EXISTS aggregated_user(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    Brands varchar(255),
                                                                    Transaction_count bigint,
                                                                    Percentage float)'''
mycursor.execute(create_query_3)
mydb.commit()

insert_query_3 = '''INSERT INTO aggregated_user(States, Years, Quarter, Brands, Transaction_count,
                                                    Percentage)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = aggre_user.values.tolist()
mycursor.executemany(insert_query_3, data)
mydb.commit()

In [ ]:
#aggre_user.columns

In [26]:
#Map_Insurance_table

create_query_4 = '''CREATE TABLE IF NOT EXISTS map_insurance(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    District varchar(255),
                                                                    Transaction_count bigint,
                                                                    Transaction_amount bigint)'''
mycursor.execute(create_query_4)
mydb.commit()

insert_query_4 = '''INSERT INTO map_insurance(States, Years, Quarter, District, Transaction_count,
                                                    Transaction_amount)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = map_insurance.values.tolist()
mycursor.executemany(insert_query_4, data)
mydb.commit()

In [ ]:
#map_insurance.columns

In [34]:
#Map_Transaction_table

create_query_5 = '''CREATE TABLE IF NOT EXISTS map_transaction(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    District varchar(255),
                                                                    Transaction_count bigint,
                                                                    Transaction_amount float)'''
mycursor.execute(create_query_5)
mydb.commit()

insert_query_5 = '''INSERT INTO map_transaction(States, Years, Quarter, District, Transaction_count,
                                                    Transaction_amount)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = map_transaction.values.tolist()
mycursor.executemany(insert_query_5, data)
mydb.commit()

In [ ]:
#map_transaction.columns

In [38]:
#Map_User_Table

create_query_6 = '''CREATE TABLE IF NOT EXISTS map_user(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    District varchar(255),
                                                                    Registered_Users bigint,
                                                                    App_Opens bigint)'''
mycursor.execute(create_query_6)
mydb.commit()

insert_query_6 = '''INSERT INTO map_user(States, Years, Quarter, District, Registered_Users,
                                                    App_Opens)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = map_user.values.tolist()
mycursor.executemany(insert_query_6, data)
mydb.commit()

In [ ]:
#map_user.columns

In [42]:
#Top_Insurance_Table

create_query_7 = '''CREATE TABLE IF NOT EXISTS top_insurance(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    Pincodes int,
                                                                    Transaction_count bigint,
                                                                    Transaction_amount bigint)'''
mycursor.execute(create_query_7)
mydb.commit()

insert_query_7 = '''INSERT INTO top_insurance(States, Years, Quarter, Pincodes, Transaction_count,
                                                    Transaction_amount)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = top_insurance.values.tolist()
mycursor.executemany(insert_query_7, data)
mydb.commit()

In [ ]:
#top_insurance.columns

In [44]:
#Top_Transaction_Table

create_query_8 = '''CREATE TABLE IF NOT EXISTS top_transaction(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    Pincodes int,
                                                                    Transaction_count bigint,
                                                                    Transaction_amount bigint)'''
mycursor.execute(create_query_8)
mydb.commit()

insert_query_8 = '''INSERT INTO top_transaction(States, Years, Quarter, Pincodes, Transaction_count,
                                                    Transaction_amount)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s,%s)'''

data = top_transaction.values.tolist()
mycursor.executemany(insert_query_8, data)
mydb.commit()

In [ ]:
#top_transaction.columns

In [48]:
#Top_User_Table

create_query_9 = '''CREATE TABLE IF NOT EXISTS top_user(States varchar(255),
                                                                    Years int,
                                                                    Quarter int,
                                                                    Pincodes int,
                                                                    Registered_Users bigint)'''
mycursor.execute(create_query_9)
mydb.commit()

insert_query_9 = '''INSERT INTO top_user(States, Years, Quarter, Pincodes, Registered_Users)
                                                    
                                                    VALUES(%s,%s,%s,%s,%s)'''

data = top_user.values.tolist()
mycursor.executemany(insert_query_9, data)
mydb.commit()

In [ ]:
#top_user.columns